### PR TITLE
Support setrlimit before executing target

### PR DESCRIPTION
**Pull request by sunxiaoguang**
For example user can specify max core file size inside docker to debug in case the contained application crashes. 
Another example is that user can increase max number of open files of dockerized application.

### CODE REVIEW

**Comment by sunxiaoguang** [comment]
Conflicts fixed. 
Please let me know if there are other reasons that this pull request shouldn't be merged.

**Comment by jwilder** [comment]
Thanks @sunxiaoguang.  I'm not sure I understand why this should be added.  Couldn't you just change the `ulimit` in the container either in a parent image's `RUN` step or before `dockerize` is started?

**Comment by sunxiaoguang** [comment]
Well, setrlimit can only change resource limit of current process and all descendants. However the control group namespace under the hood of docker actually only start from entry point or whatever the process you actually run when you start container. So a ulimit setup in RUN step wouldn't last longer enough to make it works when you start container.

**Comment by sunxiaoguang** [comment]
If you mean run ulimit actually at entry point, then it would be something like this, which definitely works, but looks strange and have to escape arguments carefully
ENTRYPOINT /bin/bash -c "ulimit -c unlimited && dockerize -template abc.template:abc.conf testapp 'long arg1' 'long arg2' "

**Comment by sunxiaoguang** [comment]
@jwilder Excuse me, in case you haven't seen the reply I sent out earlier.  Any comment is welcome.

**Comment by sunxiaoguang** [comment]
I see want you mean now. There is a ulimit command line flag for docker run, so I can change ulimit from there. Sorry.

**Pull request closed without merging**
