### PR TITLE
Add sprig template functions with prefix

### LINKED ISSUE #58: Add arithmetic functions (extend current functionality)
What do you think about implementing some basic arithmetic functions. My suggestion would be something similar to https://github.com/hashicorp/consul-template/blob/de2ebf4/template_functions.go#L727-L901

### PR DESCRIPTION
**Pull request by breml**
Add template functions from github.com/Masterminds/sprig

Implements/fixes #58

### CODE REVIEW

**Comment by breml** [comment]
@jwilder just resolved the merge conflicts for this PR and updated the README.md.

**Comment by breml** [comment]
@jwilder I would appreciate to get some feedback on this PR. Thanks.

**Comment by breml** [comment]
@jwilder would love to get some feedback.

**Comment by breml** [comment]
@jwilder could you please give me some feedback on this PR (if you don't have any interest, this is fine too, but please tell me so)

**Comment by jwilder** [comment]
@breml While sprig looks useful and has a lot of templates, I'd rather not add the dependency on it and just add the functions directly to this project that people need.

**Comment by breml** [comment]
@jwilder A little bit surprising for me, because the initial suggestion to use sprig was coming from your self (https://github.com/jwilder/dockerize/issues/58#issuecomment-250194321), but I accept it, since it is your project.

**Comment by jwilder** [comment]
@breml Sorry for the confusion. My comment was only pointing out that another person had mentioned it since it seemed related.  I thought it would be able to be used directly, but the parameter ordering and semantic changes make that more complicated.

**Pull request closed without merging**
