### PR TITLE
Add installation for Alpine images

### PR DESCRIPTION
**Pull request by mstrzele**
For me it was helpful, so maybe it's worth to mention in `README.md`  how to use
Dockerize in Alpine-based images.

### CODE REVIEW

**Comment by jwilder** [comment]
There is a `jwilder/dockerize` base image that you can extend from.  Did that not work?

**Comment by mstrzele** [comment]
No, unfortunately, I cannot change the base image (I'm using `node:alpine` and `php:alpine`).

**Comment by jwilder** [comment]
@mstrzele Ah... that makes sense.

**Comment by jwilder** [comment]
Thanks!

**Pull request merged**
