### PR TITLE
Templatizedir

### PR DESCRIPTION
**Pull request by jmahowald**
Rather than have to add in new -template commands for each template, when there are potentially multiple files, decided that it would be nice to be able to use an entire directory tree and copy that over.  

I should probably add into the README but wanted to check to see if you overall think the change makes sense.

### CODE REVIEW

**Comment by jwilder** [comment]
#57 does something similar and was merged.

**Comment by jmahowald** [comment]
I do think there are a couple of things that I had done that are still useful. I merged the [change from @breml](https://github.com/jwilder/dockerize/issues/57) and made a minor enhancement to make it able to walk a whole directory tree, and added in the unit tests that I had created. 

Can we reopen/merge or would you be open to me creating a new one?

**Comment by jwilder** [comment]
@jmahowald Sure.  Can you rebase and update the description with some details about the enhancement you've made?

**Comment by jmahowald** [comment]
I made a mess of the rebase so just created a new clean pull

**Comment by jmahowald** [comment]
Can we do https://github.com/jwilder/dockerize/pull/70 instead?  Same commits, but I just manually "rebased" them

**Pull request closed without merging**
