### PR TITLE
Access JSON Content

### LINKED ISSUE #55: Access to JSON structures
I use dockerize with cloud foundry buildpacks. Unforunately in cloud foundry the important environment variables do contain a JSON document, so I need a way to access the values within this JSON documents.

### PR DESCRIPTION
**Pull request by breml**
Added template function jsonQuery, which allows to parse a given json string into a variable, which may be a map, an array or a literal.
The query allows to access data structures as well as nested fields.

Closes #55

### CODE REVIEW

**Comment by breml** [comment]
I just updated the GLOCKFILE. As it seem, the GLOCKFILE was already outdated on master. If I update the GLOCKFILE on master, I get the following diff:

```diff
diff --git a/GLOCKFILE b/GLOCKFILE
index ce0e0ab..2cf08ca 100644
--- a/GLOCKFILE
+++ b/GLOCKFILE
@@ -1,4 +1,7 @@
+github.com/fsnotify/fsnotify f12c6236fe7b5cf6bcf30e5935d08cb079d78334
+github.com/go-fsnotify/fsnotify f12c6236fe7b5cf6bcf30e5935d08cb079d78334
 github.com/hpcloud/tail 05d326f7170255d4f0c2a57dd00268b9beeb6e59
 golang.org/x/net 972f0c5fbe4ae29e666c3f78c3ed42ae7a448b0a
+golang.org/x/sys 8f0908ab3b2457e2e15403d3697c9ef5cb4b57a9
 gopkg.in/fsnotify.v0 ea925a0a47d225b2ca7f9932b01d2ed4f3ec74f6
 gopkg.in/tomb.v1 c131134a1947e9afd9cecfe11f4c6dff0732ae58
```

The remaining changes in GLOCKFILE are due to my feature.

**Comment by breml** [comment]
And sorry I forgot to update the GLOCKFILE, I did not know this tool as I mostly use `glide` for vendoring.

**Comment by jwilder** [comment]
Did you run `glock sync -n < GLOCKFILE` beforehand?

**Comment by breml** [comment]
Yes, I did. That is the reason why only new dependencies are added in the GLOCKFILE and no existing dependencies are changed.

**Comment by breml** [comment]
@jwilder do you need something else for this PR to be merged?

**Comment by jwilder** [comment]
Thanks @breml!

**Pull request merged**
