### PR TITLE
Update golang.go/x/net to v0.33.0

### PR DESCRIPTION
**Pull request by yariksheptykin**
Closes: #220

### CODE REVIEW

**Review by jwilder — APPROVED** [review]

**Comment by jwilder** [comment]
@yariksheptykin can you update go.sum as well?

```
+golang.org/x/net v0.33.0 h1:74SYHlV8BIgHIFC/LrYkOGIwL19eTYXQ5wc6TBuO36I=
+golang.org/x/net v0.33.0/go.mod h1:HXLR5J+9DxmrqMwG9qjGCxZ+zKXxBru04zlTvWlWuN4=
```

**Comment by yariksheptykin** [comment]
Thanks for the quick reply, @jwilder ! I am quite a noob with regard to go development. I saw a `deps` target in your Makefile and hope that this is the right way to sync .mod and .sum files. I updated the PR.

**Comment by pahnin** [comment]
is there going to be a new release with this net library update? looking forward to it, thanks

**Comment by jdreesen** [comment]
Me too.

**Comment by jwilder** [comment]
v0.9.2 should have this change

**Pull request merged**
